# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iptracker < Formula
  desc ""
  homepage "https://github.com/bruceherve/iptracker"
  version "0.3"

  on_macos do
    url "https://github.com/bruceherve/iptracker/releases/download/v0.3/iptracker_0.3_darwin_all.tar.gz"
    sha256 "fb181ae82f9411209e6d162b89ae459822214eda29900d1ab624f7a4cf7cae72"

    def install
      bin.install "iptracker"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bruceherve/iptracker/releases/download/v0.3/iptracker_0.3_linux_amd64.tar.gz"
      sha256 "d755c0846001337688158d5a38e9871d07169176a3aecb9f22d32a03ac1802ce"

      def install
        bin.install "iptracker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bruceherve/iptracker/releases/download/v0.3/iptracker_0.3_linux_arm64.tar.gz"
      sha256 "d2a813284e64fbab7334bcfdbb5913207e75fd0d552ed96de2965b7f24d9be08"

      def install
        bin.install "iptracker"
      end
    end
  end
end
